export const songsArr = [
  [

    // za tumanom
    {
      lang: `BY`,
      songName: `За туманам`,
      songText: [
        `За туманам нічаго не відна... `,
        `Толькі відна дуба зелянога. `,
        `Пад тым дубам крыніца стаяла. `,
        `З той крыніцы дзеўка ваду брала. `,
        `Абраніла залато калечка. `,
        `"А хто ж тое калечка дастане, `,
        `Той са мною на рушнічак стане." `,
        `Адазваўся хлопец маладзенькі: `,
        `"А я ж тваё калечка дастану, `,
        `Я ж з табою на рушнічак стану!" `,
        `"Лепей буду палын горкі есці, `,
        `Чым з табою за столікам сесці!",`,
      ],
    },
    {
      lang: `EN`,
      songName: `Behind the fog`,
      songText: [
        `Behind the fog `,
        `Everithing is hidden... `,
        `only green oak is visible. `,
        `a stream flows under this oak. `,
        `From this steam the girl take water. `,
        `she drop on the steam her golden ring. `,
        `"And who can find this ring, `,
        `that person stand with me on a towel." `,
        `Yang men answered: `,
        `"I will find your ring. `,
        `I will stand with you on a towel!"`,
        `"It's better to eat bitter sagebrush, `,
        `than sit with you at the table!",`,
      ],
    },
    {
      lang: `PL`,
      songName: `Za mgłą`,
      songText: [
        `Za mgłą `,
        `Nie widzę nic... `,
        `Tylko widoczne `,
        `Zielony dąb. `,
        `Pod tym dębem `,
        `Strumień płynął. `,
        `Z tego strumienia `,
        `Dziewczyna wzięła wodę. `,
        `Upuszczony `,
        `Złoty pierścionek. `,
        `"A kto to jest? `,
        `Pierścień dostanie `,
        `Ten ze mną Stanie `,
        `się ręcznikiem. `,
        `odpowiedział `,
        `Młody chłopak: `,
        `"Jestem twój dostanę pierścionek `,
        `jestem z tobą `,
        `Stanę na ręczniku!" `,
        `"Wolałbym Piołun jest zjadany `,
        `A ty Usiądź przy stole!”`,
      ],
    },
  ],

//   sasonachka
  [
    {
      lang: `BY`,
      songName: `Зашумела сасоначка`,
      songText: [
        `Зашумела сасоначка `,
        `Над усходам сонца.`, 
        `Заплакала дзяўчынанька, `,
        `Гледзячы ў аконца. `,
        `"А мая ж ты, матуленька! `,
        `Чаму не будзіла, `,
        `Як першая кампанячка `,
        `У войска вырушыла?" `,
        `"А мая ж ты, дачушанька! `,
        `Таму не будзіла, `,
        `Што твой мілы ўпярод пайшоў, `,
        `Каб ты не тужыла" `,
        `"А мая ж ты, матуленька! `,
        `Не тужу, не плачу, `,
        `Толькі выйду на вулачку - `,
        `Сцежачкі не бачу!" `,
        `"А мая ж ты матуленька! `,
        `Купі ты мне шоўку- `,
        `Буду шыць і вышываці `,
        `Міламу кашульку." `,
        `Шыла-шыла, вышывала- `,
        `Не хваціла шоўку. `,
        `Любілася - кахалася, `,
        `Да не знала толку.,`,
      ],
    },
    {
      lang: `EN`,
      songName: `The pine tree made a noise`,
      songText: [
        `The pine tree made a noise `,
        `Above the sunrise. `,
        `The girl cried `,
        `Looking out the window. `,
        `"And you are mine, mother! `,
        `Why didn't you wake up `,
        `As the first company `,
        `Did you join the army?"`,
        `"And you are mine, little girl! `,
        `That's why I didn't wake up `,
        `That your sweetheart has gone `,
        `So that you don't miss" `,
        `"And you are mine, mother! `,
        `I don't miss, I don't cry `,
        `I'll just go out into the street - `,
        `I can't see the path!" `,
        `"And you are my mother! buy me silk- `,
        `I will sew and embroider Sweet shirt." `,
        `Sewed, sewed, embroidered- `,
        `There was not enough silk. `,
        `Loved - loved `,
        `I didn't know the point.,`,
      ],
    },
    {
      lang: `PL`,
      songName: `Sosna wydała dźwięk`,
      songText: [
        `Sosna wydała dźwięk `,
       ` Nad wschodem słońca. `,
       ` Dziewczyna płakała `,
        `Patrząc przez okno. `,
        `„A ty jesteś moja, mamo! `,
       ` Dla czego się nie obudziłeś `,
       ` Jako pierwsza Grupa ludzi `,
       ` Czy wstąpiłeś do armii? `,
       ` "A ty jesteś moja, mała dziewczynko! `,
       ` Dla tego się nie obudziłem `,
       ` Że twoja ukochana odeszła `,
       ` Abyś nie tęsknił" `,
       ` „A ty jesteś moja, mamo! `,
       ` Nie tęsknię, nie płaczę `,
       ` Po prostu wyjdę na ulicę - `,
       ` Nie widzę ścieżki!” `,
       ` „A ty jesteś moją matką! kup mi jedwab- `,
       ` Uszyję i wyszyję Urocza koszula.`,
       ` " Szyte, szyte, haftowane - `,
       ` Zabrakło jedwabiu. `,
       ` Kochany - kochany `,
        `Nie wiedziałem, o co chodzi.`,
      ],
    },
  ],

//   zialenaja vishnia
  [
    {
      lang: `BY`,
      songName: `Зялёная вішня`,
      songText: [
        `Зялёная вішня `,
        `З-пад кораня выйшла. `,
        `Аддала ж мяне маці `,
        `Дзе я непрывычна. `,
        `Як выйду на гору `,
        `Ды крыкну дадому: `,
        `"Вары, маці, вячэру `,
       ` Шчэ і на маю долю!" `,
       ` "Ты думаеш, мама. `,
       ` Што я тут не плачу - `,
       ` За горкімі слязамі `,
       ` Я свету не бачу. `,
       ` Ты думаеш, мама, `,
       ` Што я тут раюю- `,
        `Прыдзі, падзівіся, `,
       ` Як я тут гарую. `,
       ` Успамяні ж мяне, мама, `,
       ` Хоць раз у суботу, `,
       ` Як я успамінаю, `,
       ` Ідучы на работу. `,
       ` Успамяні ж мяне, мама, `,
       ` Хоць раз у нядзелю, `,
       ` Як я успамінаю `,
       ` Сцелючы пасцелю. `,
       ` Успамяні ж мяне, мама, `,
       ` Хоць раз у аўторак, `,
       ` Як я успамінаю на дзень `,
       ` Разоў сорак.",`,
      ],
    },
    {
      lang: `EN`,
      songName: `A green cherry`,
      songText: [
       ` A green cherry `,
       ` came out from under the root.`,
       ` My mother gave me where`,
       ` I am not used to.`,
       ` As I climb the mountain,`,
       ` I will shout home:`,
       ` "Cook, mother, dinner for me too!"`,
       ` "You think, mom.`,
       ` That I'm not crying here -`,
       ` Behind the bitter tears`,
      `  I do not see the world.`,
      `  Do you think, mom,`,
       ` What am I recommending here-`,
       ` Come, see how I burn here.`,
       ` Remember me, mother,`,
      `  At least once on Saturday,`,
        `As I remember, going to work.`,
       ` Remember me, mom,`,
       ` At least once on Sunday,`,
       ` As I remember,`,
       ` I was lying in bed.`,
       ` Remember me, mom,`,
       ` even once on Tuesday,`,
       ` As I remember on the day`,
       ` of the Forty Times.",`,
      ],
    },
    {
      lang: `PL`,
      songName: `Zielona wiśnia`,
      songText: [
        `Spod korzenia wyszła`,
        ` zielona wiśnia. `,
        ` Moja mama dała mi miejsce, `,
        ` do którego nie jestem przyzwyczajony. `,
        ` Gdy wejdę na górę, `,
        ` krzyknę do domu: `,
        ` "Gotuj, mamo, obiad `,
        ` dla mnie też!" `,
        ` "Myślisz, mamo. `,
        ` Że tu nie płaczę - `,
        ` Za gorzkimi łzami nie widzę świata. `,
        ` Czy myślisz, mamo, co tutaj polecam- `,
        ` Chodź, zobacz jak tu płonę. `,
        ` Zapamiętaj mnie mamo, `,
        ` przynajmniej raz w sobotę, `,
        ` Jak pamiętam do pracy. `,
        ` Zapamiętaj mnie mamo, `,
        ` przynajmniej raz w niedzielę, `,
        ` Jak pamiętam leżałem w łóżku. `,
        ` Zapamiętaj mnie mamo, `,
        ` chociaż raz we wtorek, `,
        ` Jak pamiętam w dniu czterdziestu czasów”.`,
      ],
    },
  ],

//   ishow milenki
  [
    {
      lang: `BY`,
      songName: `Ішоў міленькі`,
      songText: [
        `Ішоў міленькі лужочкам,`,
        `А я млада беражком.`,
        `Махнуў міленькі платочкам,`,
        `А я праваю рукой.`,
        `Чэраз рэчку падай ручку,`,
        `Чэраз быструю раку.`,
        `Гэта рэчачка шырока,`,
        `Да крутыя берага.`,
        `Гэта рэчка рассярчала,`,
        `Як ударыла вална, `,
        `Як ударыла вална `,
        `Да ў крутыя берага. `,
        `Наступае маё ўрэмя `,
        `Усё халодная зіма, `,
        `Нету следу на дарожцы, `,
        `Майго мілага няма.`,
    ],
    },
    {
      lang: `EN`,
      songName: `The cute one was walking`,
      songText: [
        `The cute one was walking along the lawn, `,
        `and I was young along the shore. `,
        `He waved a cute handkerchief, `,
        `and I waved my right hand. `,
        `Pass the pen across the river, `,
        `Across the swift river. `,
        `This river is wide, with steep banks. `,
        `This river swelled, `,
        `Like a wave hit, `,
        `How the wave Ka hit the steep shores. `,
        `My time is coming `,
        `All the cold winter `,
        `There is no trace on the path, `,
        `My darling is gone.`,
      ],
    },
    {
      lang: `PL`,
      songName: `Urocza spacerowała`,
      songText: [
        `Urocza spacerowała po trawniku, `,
        `a ja byłam młoda na brzegu. `,
        `Pomachał mi uroczą chusteczką, `,
        `a ja prawą ręką. `,
        `Przełóż pióro przez rzekę, `,
        `przez wartką rzekę. `,
        `Ta rzeka jest szeroka, `,
        `o stromych brzegach. `,
        `Ta rzeka wezbrała, `,
        `jak uderzenie fali, `,
        `Jak fala Ka uderzyła `,
        `w strome brzegi. `,
        `Mój czas nadchodzi `,
        `Cała mroźna zima `,
        `Nie ma śladu na ścieżce, `,
       ` Moja ukochana odeszła.`,
      ],
    },
  ],

//   a u sadze ruzsha
  [
    {
      lang: `BY`,
      songName: `А ў садзе ружа`,
      songText: [
        `А ў садзе ружа, `,
        `Мілы мой Божа - `,
        `Несчасна мая Доль. `,
        `Не порадзіны, `,
        `Не колядзіны - `,
        `Не родныя Мамкі. `,
        `Пасылала б я `,
        `Чорну галачку `,
        `На той свет `,
        `Па мамку. `,
        `Сакаліначку `,
        `На Украіначку `,
        `На сваю Радзімку. `,
        `Саколік ляціць `,
        `Не далётае `,
        `Мамачка даўно Ждзёць. `,
        `"Ой, рада б я ўстаць, `,
        `Мае дзіцяці - `,
        `Парадак Павесці. `,
        `Бо сыра зямля `,
        `На грудзі лягла - `,
        `Не магу я Устаці. `,
        `Сасновы дошкі `,
        `Сціснулі ножкі - `,
        `Не магу пайсці, Ісці."`,
    ],
    },
    {
      lang: `EN`,
      songName: `And there is a rose in the garden`,
      songText: [
        `And there is a rose in the garden, `,
        `my dear God - `,
        `My fate is unfortunate. `,
        `Not families, not Christmas - `,
        `Not native Mom. `,
        `I would send a black check mark `,
        `To the other world, Mom. `,
        `Sakolinachku On Ukrainachku `,
        `To my homeland. `,
        `The falcon flies. `,
        `It does not fly `,
        `Mommy has been waiting `,
        `for a long time. `,
        `"Oh, I wish I could get up, `,
        `My children - The order to bring. `,
        `Because the wet earth lay on the chest - `,
        `I can not get up. `,
        `Pine boards Squeezed the legs - `,
        `I can't go, Go."`,
      ],
    },
    {
      lang: `PL`,
      songName: `A w ogrodzie jest róża`,
      songText: [
       `A w ogrodzie jest róża, `,
       `mój drogi Boże - `,
       `Mój los jest niefortunny. `,
       `Nie rodziny, nie `,
       `Boże Narodzenie - `,
       `Nie rodzima mama. `,
       `Wysłałbym czarny znacznik wyboru `,
       `Na tamten świat, mamo. `,
       `Sakolinachku na Ukrainiechku `,
       `Do mojej ojczyzny. `,
       `Sokół leci, nie lata `,
       `Mamusia czekała bardzo długo. `,
       `"Och, chciałbym móc wstać, `,
       `Moje dzieci - Rozkaz przyniesienia. `,
       `Ponieważ mokra ziemia leżała na piersi - `,
       `Nie mogę wstać. `,
       `Deski sosnowe `,
       `Ściśnięte nogi - `,
       `Nie mogę iść, Idź."`,
      ],
    },
  ],

//   garela sosna
  [
    {
      lang: `BY`,
      songName: `Гарэла сосна, Палала`,
      songText: [
        `Агу, вясна! `,
        `Агу, красна! `,
        `А што ж ты нам прынесла? `,
        `Весначуха-балбатуха, `,
        `Воран крача- Сыра хоча! `,
        `Сыра хоча, `,
        `Дзеўка плача - Замуж хоча! `,
        `Не крач, воран - Накрачэшся! `,
        `Не плач, дзеўка - Наплачэшся! `,
        `Воран крача-Сыра з'еўшы, `,
        `Дзеўка плача Сына меўшы. `,
        ` `,
        `Гарэла сосна, Палала. `,
        `Пад ёю дзеўка Стаяла. `,
        `Русую косу Часала. `,
        `"Ой, косы-косы `,
        `Вы ж мае! `,
        `Мала служылі `,
        `Вы ў мяне! `,
        `Ой, больш служыць `,
        `Не будзеце! `,
        `Пад белы вялён (вэлюм) `,
        `Пойдзеце!"`,
    ],
    },
    {
      lang: `EN`,
      songName: `The pine was burning`,
      songText: [
       `Ah, spring! `,
       `Oh, it's red! `,
       `And what did you bring us? `,
       `Spring-eared chatterbox, `,
       `Crow croaks - Cheese wants! `,
       `cheese wants `,
       `The girl is crying - She wants to get married! `,
       `Don't stop, crow - you will stop! `,
       `Don't cry, girl - You'll cry! `,
       `The raven raven, having eaten the cheese, `,
       `A girl is crying with her son. `,
       `The pine was burning, Palala. `,
       `A girl was standing under her. `,
       `Chasala's red braid. `,
       `"Oh, braids, braids, you are mine! `,
       `You served me a little!`,
       `Oh, you won't serve anymore! `,
       `Under the white veil (veil) Go!"`,
      ],
    },
    {
      lang: `PL`,
      songName: `A w ogrodzie jest róża`,
      songText: [
        `Ach, wiosna! `,
        `Och, jest czerwony! `,
        `A co nam przyniosłeś? `,
        `Sprężynowiec gadułą, `,
        `Wrona rechocze - `,
        `Ser chce! `,
        `ser chce `,
        `Dziewczyna płacze - `,
        `chce wyjść za mąż! `,
        `Nie przestawaj, wrona - `,
        `przestaniesz! `,
        `Nie płacz dziewczyno - `,
        `będziesz płakać! `,
        `Kruk kruk, po zjedzeniu sera, `,
        `Dziewczynka płacze z synem. `,
        `Sosna płonęła, Palala. `,
        `Pod nią stała dziewczyna. `,
        `Rosyjski warkocz Chasali. `,
        `„Och, warkocze, warkocze, jesteś mój! `,
        `Trochę mi służyłeś! `,
        `Och, już nie będziesz służyć! `,
        `Pod białą zasłoną (welon) Idź!"`,
      ],
    },
  ],

//   los
  [
    {
      lang: `BY`,
      songName: `Ой злавілі лося ў гаросе`,
      songText: [
        `Ой злавілі `,
        `Ды сівогога лося У гаросе. `,
        `Як і пачула `,
        `Яго старая ласіца У лузе. `,
        `Як і кінула `,
        `Крутыя рогі Пад ногі. `,
        `"Няхай мае `,
        `Крутыя рогі Прападуць! `,
        `Куды ж майго `,
        `Сівога лася Павядуць?"`,
    ],
    },
    {
      lang: `EN`,
      songName: `Oh, they caught a gray moose`,
      songText: [
       `Oh, they caught `,
       `a gray moose in the forest. `,
       `As the old weasel`,
       `heard it in the meadow. `,
       `As she threw `,
       `the steep horns `,
       `Under her feet. `,
       `"Let my Cool Horns `,
       `Be Vanished! `,
       `Where will they `,
       `take my gray elk?"`,
      ],
    },
    {
      lang: `PL`,
      songName: `Och, złapali szarego łosia w lesie.`,
      songText: [
        `Och, złapali `,
        `szarego łosia w lesie. `,
        `Jak stara łasica `,
        `usłyszała to na łące. `,
        `Gdy rzuciła strome rogi `,
        `pod jej stopy. `,
        `„Niech moje fajne rogi znikną! `,
        `Dokąd zabiorą `,
        `mojego szarego łosia?,`,
      ],
    },
  ],
];
