export const songsArr = [
  [

    // za tumanom
    {
      lang: `BY`,
      songName: `За туманам`,
      songText: [
        `За туманам нічаго не відна... `,
        `Толькі відна дуба зелянога. `,
        `Пад тым дубам крыніца стаяла. `,
        `З той крыніцы дзеўка ваду брала. `,
        `Абраніла залато калечка. `,
        `"А хто ж тое калечка дастане, `,
        `Той са мною на рушнічак стане." `,
        `Адазваўся хлопец маладзенькі: `,
        `"А я ж тваё калечка дастану, `,
        `Я ж з табою на рушнічак стану!" `,
        `"Лепей буду палын горкі есці, `,
        `Чым з табою за столікам сесці!",`,
      ],
    },
    {
      lang: `EN`,
      songName: `Behind the fog`,
      songText: [
        `Behind the fog `,
        `Everithing is hidden... `,
        `only green oak is visible. `,
        `a stream flows under this oak. `,
        `From this steam the girl take water. `,
        `she drop on the steam her golden ring. `,
        `"And who can find this ring, `,
        `that person stand with me on a towel." `,
        `Yang men answered: `,
        `"I will find your ring. `,
        `I will stand with you on a towel!"`,
        `"It's better to eat bitter sagebrush, `,
        `than sit with you at the table!",`,
      ],
    },
    {
      lang: `PL`,
      songName: `Za mgłą`,
      songText: [
       `Za mgłą`,
       `Nic nie widać.`,
       `Tylko jeden`,
       `Dąb zielony.`,
       `Pod tym dębem`,
       `Źródło bije.`,
       `Z tego źródła`,
       `Dziewczyna wodę brała.`,
       `Złoty pierścionek`,
       `Upuściła.`,
       `"Kto mój pierścionek `,
       `Odnajdzie,`,
       `Ten na kobiercu `,
       `ze mną się znajdzie”`,
       `Odrzekł jej chłopak`,
       `młody:`,
       `"Pierścionek twój `,
       `odnajdę,`,
       `Na kobiercu `,
       `z tobą się znajdę!"`,
      ],
    },
  ],


//   sasonachka
  [
    {
      lang: `BY`,
      songName: `Зашумела сасоначка`,
      songText: [
        `Зашумела сасоначка `,
        `Над усходам сонца.`, 
        `Заплакала дзяўчынанька, `,
        `Гледзячы ў аконца. `,
        `"А мая ж ты, матуленька! `,
        `Чаму не будзіла, `,
        `Як першая кампанячка `,
        `У войска вырушыла?" `,
        `"А мая ж ты, дачушанька! `,
        `Таму не будзіла, `,
        `Што твой мілы ўпярод пайшоў, `,
        `Каб ты не тужыла" `,
        `"А мая ж ты, матуленька! `,
        `Не тужу, не плачу, `,
        `Толькі выйду на вулачку - `,
        `Сцежачкі не бачу!" `,
        `"А мая ж ты матуленька! `,
        `Купі ты мне шоўку- `,
        `Буду шыць і вышываці `,
        `Міламу кашульку." `,
        `Шыла-шыла, вышывала- `,
        `Не хваціла шоўку. `,
        `Любілася - кахалася, `,
        `Да не знала толку.,`,
      ],
    },
    {
      lang: `EN`,
      songName: `The pine tree made a noise`,
      songText: [
        `The pine tree made a noise `,
        `Above the sunrise. `,
        `The girl cried `,
        `Looking out the window. `,
        `"And you are mine, mother! `,
        `Why didn't you wake up `,
        `As the first company `,
        `Did you join the army?"`,
        `"And you are mine, little girl! `,
        `That's why I didn't wake up `,
        `That your sweetheart has gone `,
        `So that you don't miss" `,
        `"And you are mine, mother! `,
        `I don't miss, I don't cry `,
        `I'll just go out into the street - `,
        `I can't see the path!" `,
        `"And you are my mother! buy me silk- `,
        `I will sew and embroider Sweet shirt." `,
        `Sewed, sewed, embroidered- `,
        `There was not enough silk. `,
        `Loved - loved `,
        `I didn't know the point.,`,
      ],
    },
    {
      lang: `PL`,
      songName: `Zaszumiała sosenka`,
      songText: [
        `Zaszumiała sosenka`,
        `O wschodzie słońca.`,
        `Zapłakała dziewczyna`,
        `Przez okno popatrzyła.`,
        `"Moja matuleńko,`,
        `Czemuż nie budziłaś`,
        `Gdy pierwsza kompania`,
        `do wojska ruszyła"`,
        `"Moja ty córusiu,`,
        `Temu nie budziłam`,
        `bo twój miły pierwszy poszedł,`,
        `żebyś nie tęskniła"`,
        `"Moja matuleńko!`,
        `Nie tęsknię, nie płaczę,`,
        `Wyjdę na ulicę, `,
        `Ścieżki nie zobaczę!`,
        `"Moja matuleńko,`,
        `Kup ty mi jedwabiu!`,
        `Będę szyć, haftować`,
        `miłemu koszulę!”`,

      ],
    },
  ],

//   zialenaja vishnia
  [
    {
      lang: `BY`,
      songName: `Зялёная вішня`,
      songText: [
        `Зялёная вішня `,
        `З-пад кораня выйшла. `,
        `Аддала ж мяне маці `,
        `Дзе я непрывычна. `,
        `Як выйду на гору `,
        `Ды крыкну дадому: `,
        `"Вары, маці, вячэру `,
        `Шчэ і на маю долю!" `,
        `"Ты думаеш, мама. `,
        `Што я тут не плачу - `,
        `За горкімі слязамі `,
        `Я свету не бачу. `,
        `Ты думаеш, мама, `,
        `Што я тут раюю- `,
        `Прыдзі, падзівіся, `,
        `Як я тут гарую. `,
        `Успамяні ж мяне, мама, `,
        `Хоць раз у суботу, `,
        `Як я успамінаю, `,
        `Ідучы на работу. `,
        `Успамяні ж мяне, мама, `,
        `Хоць раз у нядзелю, `,
        `Як я успамінаю `,
        `Сцелючы пасцелю. `,
        `Успамяні ж мяне, мама, `,
        `Хоць раз у аўторак, `,
        `Як я успамінаю на дзень `,
        `Разоў сорак.",`,
      ],
    },
    {
      lang: `EN`,
      songName: `A green cherry`,
      songText: [
       ` A green cherry `,
       ` came out from under the root.`,
       ` My mother gave me where`,
       ` I am not used to.`,
       ` As I climb the mountain,`,
       ` I will shout home:`,
       ` "Cook, mother, dinner for me too!"`,
       ` "You think, mom.`,
       ` That I'm not crying here -`,
       ` Behind the bitter tears`,
      `  I do not see the world.`,
      `  Do you think, mom,`,
       ` What am I recommending here-`,
       ` Come, see how I burn here.`,
       ` Remember me, mother,`,
      `  At least once on Saturday,`,
        `As I remember, going to work.`,
       ` Remember me, mom,`,
       ` At least once on Sunday,`,
       ` As I remember,`,
       ` I was lying in bed.`,
       ` Remember me, mom,`,
       ` even once on Tuesday,`,
       ` As I remember on the day`,
       ` of the Forty Times.",`,
      ],
    },
    {
      lang: `PL`,
      songName: `Zielona wiśnia`,
      songText: [
        `Zielona wiśnia`,
        `Spod korzenia wyszła`,
        `Oddała mnie matka`,
        `Tam gdzie nie przywykłam.`,
        `Wyjdę ja na górę`,
        `Krzyknę w stronę domu`,
        `„Szykuj, mamo, obiad,`,
        `Gotuj mi mą dolę"`,
        `"Myślisz, może, mamo,`,
        `Że ja tu nie płaczę`,
        `Za gorzkimi łzami`,
        `Świata nie zobaczę."`,
        `"Czy ty myślisz, mamo,`,
        `Że mi tu jak w raju?`,
        `Chodź i sama zobacz`,
        `Jak ja tutaj płonę."`,
        `"Wspomnij o mnie, matko,`,
        `Chociaż raz w sobotę`,
        `Tak jak ja wspominam`,
        `Idąc do roboty"`,
        `"Wspomnij o mnie, matko,`,
        `Chociaż raz w niedzielę`,
        `Tak jak ja wspominam`,
        `Kiedy łóżko ścielę."`,
        `"Wspomnij o mnie, matko,`,
        `Chociaż raz we wtorek`,
        `Tak jak ja wspominam`,
        `W dzień razy czterdzieści...”`,
      ],
    },
  ],

//   ishow milenki
  [
    {
      lang: `BY`,
      songName: `Ішоў міленькі`,
      songText: [
        `Ішоў міленькі лужочкам,`,
        `А я млада беражком.`,
        `Махнуў міленькі платочкам,`,
        `А я праваю рукой.`,
        `Чэраз рэчку падай ручку,`,
        `Чэраз быструю раку.`,
        `Гэта рэчачка шырока,`,
        `Да крутыя берага.`,
        `Гэта рэчка рассярчала,`,
        `Як ударыла вална, `,
        `Як ударыла вална `,
        `Да ў крутыя берага. `,
        `Наступае маё ўрэмя `,
        `Усё халодная зіма, `,
        `Нету следу на дарожцы, `,
        `Майго мілага няма.`,
    ],
    },
    {
      lang: `EN`,
      songName: `The cute one was walking`,
      songText: [
        `The cute one was walking along the lawn, `,
        `and I was young along the shore. `,
        `He waved a cute handkerchief, `,
        `and I waved my right hand. `,
        `Pass the pen across the river, `,
        `Across the swift river. `,
        `This river is wide, with steep banks. `,
        `This river swelled, `,
        `Like a wave hit, `,
        `How the wave Ka hit the steep shores. `,
        `My time is coming `,
        `All the cold winter `,
        `There is no trace on the path, `,
        `My darling is gone.`,
      ],
    },
    {
      lang: `PL`,
      songName: `Szedł mileńki po łące`,
      songText: [
        `Szedł mileńki po łące`,
        `A ja młoda - brzegiem.`,
        `Machnął mileńki chusteczką`,
        `A ja ręką prawą.`,
        `Podaj rękę przez rzeczkę`,
        `Przez bystrą rzekę.`,
        `Rzeczka jest szeroka`,
        `Strome brzegi ma.`,
        `Rzeka się rozzłościła`,
        `Kiedy fala uderzyła,`,
        `Kiedy fala uderzyła`,
        `W strome brzegi dwa.`,
        `Idzie już mój czas`,
        `Idzie mroźna zima.`,
        `Nie ma śladu na drodze.`,
        `Nie ma mego miłego.`,
        
      ],
    },
  ],

//   a u sadze ruzsha
  [
    {
      lang: `BY`,
      songName: `А ў садзе ружа`,
      songText: [
        `А ў садзе ружа, `,
        `Мілы мой Божа - `,
        `Несчасна мая доль. `,
        `Не порадзіны, `,
        `Не колядзіны - `,
        `Не родныя мамкі. `,
        `Пасылала б я `,
        `Чорну галачку `,
        `На той свет `,
        `Па мамку. `,
        `Сакаліначку `,
        `На Украіначку `,
        `На сваю радзімку. `,
        `Саколік ляціць `,
        `Не далётае `,
        `Мамачка даўно ждзёць. `,
        `"Ой, рада б я ўстаць, `,
        `Мае дзіцяці - `,
        `Парадак павесці. `,
        `Бо сыра зямля `,
        `На грудзі лягла - `,
        `Не магу я Устаці. `,
        `Сасновы дошкі `,
        `Сціснулі ножкі - `,
        `Не магу пайсці, ісці."`,
    ],
    },
    {
      lang: `EN`,
      songName: `And there is a rose in the garden`,
      songText: [
        `And there is a rose in the garden, `,
        `my dear God - `,
        `My fate is unfortunate. `,
        `Not families, not Christmas - `,
        `Not native Mom. `,
        `I would send a black check mark `,
        `To the other world, Mom. `,
        `Sakolinachku On Ukrainachku `,
        `To my homeland. `,
        `The falcon flies. `,
        `It does not fly `,
        `Mommy has been waiting `,
        `for a long time. `,
        `"Oh, I wish I could get up, `,
        `My children - The order to bring. `,
        `Because the wet earth lay on the chest - `,
        `I can not get up. `,
        `Pine boards Squeezed the legs - `,
        `I can't go, Go."`,
      ],
    },
    {
      lang: `PL`,
      songName: `Rośnie róża w sadzie`,
      songText: [
        `Rośnie róża w sadzie`,
        `O mój drogi Boże!`,
        `Nieszczęsny mój los.`,
        `Ani chrzcin,`,
        `Ani kolędy,`,
        `Ani rodzonej Matki.`,
        `Posłałabym`,
        `Czarnego ptaka`,
        `Na ten świat`,
        `Po mamę.`,
        `Sokoła`,
        `Do Ukrainy`,
        `Do swojej ojczyzny.`,
        `Leci sokół`,
        `Nie doleci`,
        `Mama długo czeka.`,
        `"Och, chciałbym ja wstać,`,
        `Moje dziecko,`,
        `Porządki robić!`,
        `Ale święta ziemia`,
        `Ciąży mi na piersi`,
        `Nie mogę ja wstać!`,
        `Deski sosnowe`,
        `Ścisnęły mi nogi`,
        `Nie mogę ja pójść."`,
      ],
    },
  ],

//   garela sosna
  [
    {
      lang: `BY`,
      songName: `Гарэла сосна, палала`,
      songText: [
        `Агу, вясна! `,
        `Агу, красна! `,
        `А што ж ты нам прынесла? `,
        `Весначуха-балбатуха, `,
        `Воран крача- сыра хоча! `,
        `Дзеўка плача - замуж хоча! `,
        `Не крач, воран - накрачэшся! `,
        `Не плач, дзеўка - наплачэшся! `,
        `Воран крача-сыра з'еўшы, `,
        `Дзеўка плача сына меўшы. `,
        ` `,
        `Гарэла сосна, палала. `,
        `Пад ёю дзеўка стаяла. `,
        `Русую косу часала. `,
        `"Ой, косы-косы `,
        `Вы ж мае! `,
        `Мала служылі `,
        `Вы ў мяне! `,
        `Ой, больш служыць `,
        `Не будзеце! `,
        `Пад белы вялён (вэлюм) `,
        `Пойдзеце!"`,
    ],
    },
    {
      lang: `EN`,
      songName: `The pine was burning`,
      songText: [
       `Ah, spring! `,
       `Oh, it's red! `,
       `And what did you bring us? `,
       `Spring-eared chatterbox, `,
       `Crow croaks - Cheese wants! `,
       `cheese wants `,
       `The girl is crying - She wants to get married! `,
       `Don't stop, crow - you will stop! `,
       `Don't cry, girl - You'll cry! `,
       `The raven raven, having eaten the cheese, `,
       `A girl is crying with her son. `,
       `The pine was burning, Palala. `,
       `A girl was standing under her. `,
       `Chasala's red braid. `,
       `"Oh, braids, braids, you are mine! `,
       `You served me a little!`,
       `Oh, you won't serve anymore! `,
       `Under the white veil (veil) Go!"`,
      ],
    },
    {
      lang: `PL`,
      songName: `Płonęła sosna`,
      songText: [
        `Oj, wiosna!`,
        `Oj, piękna!`,
        `Co tym nam`,
        `Przyniosłaś?`,
        `Wiosnaczucha-bołbotucha`,
        `Kracze kruk`,
        `Sera chce!`,
        `Sera chce,`,
        `Płacze dziewczyna`,
        `Za mąż chce.`,
        `Nie kracz, kruku`,
        `Jeszcze się nakraczesz,`,
        `Nie płacz dziewczyno,`,
        `Jeszcze się napłaczesz!`,
        `Kracze kruk,`,
        `Zjadł sera,`,
        `Dziewczyna płacze`,
        `syna urodziła.`,
        ``,
        `Płonęła sosna,`,
        `Płonęła.`,
        `Pod nią dziewczyna`,
        `Stanęła.`,
        `Jasny warkocz czesała.`,
        `Oj, warkocze-warkocze`,
        `Wy moje!`,
        `Mało służyłyście`,
        `Wy u mnie!`,
        `Oj, dłużej służyć`,
        `nie będziecie`,
        `Pod biały welon`,
        `Pójdziecie!`,
      ],
    },
  ],

//   los
  [
    {
      lang: `BY`,
      songName: `Ой злавілі лося ў гаросе`,
      songText: [
        `Ой злавілі `,
        `Ды сівогога лося У гаросе. `,
        `Як і пачула `,
        `Яго старая ласіца У лузе. `,
        `Як і кінула `,
        `Крутыя рогі пад ногі. `,
        `"Няхай мае `,
        `Крутыя рогі прападуць! `,
        `Куды ж майго `,
        `Сівога лася павядуць?"`,
    ],
    },
    {
      lang: `EN`,
      songName: `Oh, they caught a gray moose`,
      songText: [
       `Oh, they caught `,
       `a gray moose in the forest. `,
       `As the old weasel`,
       `heard it in the meadow. `,
       `As she threw `,
       `the steep horns `,
       `Under her feet. `,
       `"Let my Cool Horns `,
       `Be Vanished! `,
       `Where will they `,
       `take my gray elk?"`,
      ],
    },
    {
      lang: `PL`,
      songName: `Oj, złapali siwego łosia w grochu`,
      songText: [
        `Oj, złapali `,
        `siwego łosia w grochu.`,
        `Jak usłyszała`,
        `to jego stara`,
        `łosza na łące.`,
        `zrzuciła swoje`,
        `przepiękne rogi`,
        `pod nogi.`,
        `"Niechaj te rogi`,
        `me piękne rogi`,
        `Przepadną!`,
        `Tam gdzie mojego`,
        `siwego łosia`,
        `Prowadzą."`,

      ],
    },
  ],
];


