export const songsArr = [
  [

    // za tumanom
    {
      lang: `PL`,
      songName: `Za mgłą`,
      songText: [
       `Za mgłą`,
       `Nic nie widać.`,
       `Tylko jeden`,
       `Dąb zielony.`,
       `Pod tym dębem`,
       `Źródło bije.`,
       `Z tego źródła`,
       `Dziewczyna wodę brała.`,
       `Złoty pierścionek`,
       `Upuściła.`,
       `"Kto mój pierścionek `,
       `Odnajdzie,`,
       `Ten na kobiercu `,
       `ze mną się znajdzie”`,
       `Odrzekł jej chłopak`,
       `młody:`,
       `"Pierścionek twój `,
       `odnajdę,`,
       `Na kobiercu `,
       `z tobą się znajdę!"`,
      ],
    },
    {
      lang: `BY`,
      songName: `За туманам`,
      songText: [
        `За туманам нічаго не відна... `,
        `Толькі відна дуба зелянога. `,
        `Пад тым дубам крыніца стаяла. `,
        `З той крыніцы дзеўка ваду брала. `,
        `Абраніла залато калечка. `,
        `"А хто ж тое калечка дастане, `,
        `Той са мною на рушнічак стане." `,
        `Адазваўся хлопец маладзенькі: `,
        `"А я ж тваё калечка дастану, `,
        `Я ж з табою на рушнічак стану!" `,
        `"Лепей буду палын горкі есці, `,
        `Чым з табою за столікам сесці!",`,
      ],
    },
    {
      lang: `EN`,
      songName: `Behind the fog`,
      songText: [
        `Behind the fog`,
        `I can not see anything.`,
        `You can only see`,
        `Green oak.`,
        `There was the sour (krynitsa)`,
        `Under that oak tree`,
        `From that creep`,
        `The girl was taking water.`,
        `Dropped a gold ring.`,
        `"Who will get my ring`,
        `The one with me will become a towel (will become my betrothed) "`,
        `The young guy responded:`,
        `"I'll get your ring,`,
        `I'll stand on a towel with you!"`,
      ],
    },
  ],


//   sasonachka
  [
    {
      lang: `PL`,
      songName: `Zaszumiała sosenka`,
      songText: [
        `Zaszumiała sosenka`,
        `O wschodzie słońca.`,
        `Zapłakała dziewczyna`,
        `Przez okno popatrzyła.`,
        `"Moja matuleńko,`,
        `Czemuż nie budziłaś`,
        `Gdy pierwsza kompania`,
        `do wojska ruszyła"`,
        `"Moja ty córusiu,`,
        `Temu nie budziłam`,
        `bo twój miły pierwszy poszedł,`,
        `żebyś nie tęskniła"`,
        `"Moja matuleńko!`,
        `Nie tęsknię, nie płaczę,`,
        `Wyjdę na ulicę, `,
        `Ścieżki nie zobaczę!`,
        `"Moja matuleńko,`,
        `Kup ty mi jedwabiu!`,
        `Będę szyć, haftować`,
        `miłemu koszulę!”`,

      ],
    },
    {
      lang: `BY`,
      songName: `Зашумела сасоначка`,
      songText: [
        `Зашумела сасоначка `,
        `Над усходам сонца.`, 
        `Заплакала дзяўчынанька, `,
        `Гледзячы ў аконца. `,
        `"А мая ж ты, матуленька! `,
        `Чаму не будзіла, `,
        `Як першая кампанячка `,
        `У войска вырушыла?" `,
        `"А мая ж ты, дачушанька! `,
        `Таму не будзіла, `,
        `Што твой мілы ўпярод пайшоў, `,
        `Каб ты не тужыла" `,
        `"А мая ж ты, матуленька! `,
        `Не тужу, не плачу, `,
        `Толькі выйду на вулачку - `,
        `Сцежачкі не бачу!" `,
        `"А мая ж ты матуленька! `,
        `Купі ты мне шоўку- `,
        `Буду шыць і вышываці `,
        `Міламу кашульку." `,
        `Шыла-шыла, вышывала- `,
        `Не хваціла шоўку. `,
        `Любілася - кахалася, `,
        `Да не знала толку.,`,
      ],
    },
    {
      lang: `EN`,
      songName: `The pine tree made a noise`,
      songText: [
        `The pine made a noise`,
        `Over the sunrise.`,
        `The girl cried`,
        `Looking out the window.`,
        `"And you are mine, mommy,`,
        `Why didn't you wake up`,
        `As the first company`,
        `moved into the army"`,
        `"And you are my daughter,`,
        `That's why I didn't wake up`,
        `that your darling went ahead,`,
        `so that you do not grieve (sad)."`,
        `"And you are mine, Mommy!`,
        `I'm not sad, I'm not crying`,
        `I'll just go outside`,
        `I don't see the path!`,
        `"And you are my mother,`,
        `Buy me some silk!`,
        `I will sew and embroider`,
        `cute shirt!`,
      ],
    },
  ],

//   zialenaja vishnia
  [
    {
      lang: `PL`,
      songName: `Zielona wiśnia`,
      songText: [
        `Zielona wiśnia`,
        `Spod korzenia wyszła`,
        `Oddała mnie matka`,
        `Tam gdzie nie przywykłam.`,
        `Wyjdę ja na górę`,
        `Krzyknę w stronę domu`,
        `„Szykuj, mamo, obiad,`,
        `Gotuj mi mą dolę"`,
        `"Myślisz, może, mamo,`,
        `Że ja tu nie płaczę`,
        `Za gorzkimi łzami`,
        `Świata nie zobaczę."`,
        `"Czy ty myślisz, mamo,`,
        `Że mi tu jak w raju?`,
        `Chodź i sama zobacz`,
        `Jak ja tutaj płonę."`,
        `"Wspomnij o mnie, matko,`,
        `Chociaż raz w sobotę`,
        `Tak jak ja wspominam`,
        `Idąc do roboty"`,
        `"Wspomnij o mnie, matko,`,
        `Chociaż raz w niedzielę`,
        `Tak jak ja wspominam`,
        `Kiedy łóżko ścielę."`,
        `"Wspomnij o mnie, matko,`,
        `Chociaż raz we wtorek`,
        `Tak jak ja wspominam`,
        `W dzień razy czterdzieści...”`,
      ],
    },
    {
      lang: `BY`,
      songName: `Зялёная вішня`,
      songText: [
        `Зялёная вішня `,
        `З-пад кораня выйшла. `,
        `Аддала ж мяне маці `,
        `Дзе я непрывычна. `,
        `Як выйду на гору `,
        `Ды крыкну дадому: `,
        `"Вары, маці, вячэру `,
        `Шчэ і на маю долю!" `,
        `"Ты думаеш, мама. `,
        `Што я тут не плачу - `,
        `За горкімі слязамі `,
        `Я свету не бачу. `,
        `Ты думаеш, мама, `,
        `Што я тут раюю- `,
        `Прыдзі, падзівіся, `,
        `Як я тут гарую. `,
        `Успамяні ж мяне, мама, `,
        `Хоць раз у суботу, `,
        `Як я успамінаю, `,
        `Ідучы на работу. `,
        `Успамяні ж мяне, мама, `,
        `Хоць раз у нядзелю, `,
        `Як я успамінаю `,
        `Сцелючы пасцелю. `,
        `Успамяні ж мяне, мама, `,
        `Хоць раз у аўторак, `,
        `Як я успамінаю на дзень `,
        `Разоў сорак.",`,
      ],
    },
    {
      lang: `EN`,
      songName: `A green cherry`,
      songText: [
       ` A green cherry `,
       `Came out from under the root`,
       `Mother gave me`,
       `Where I'm not used to.`,
       `I will go to the mountain`,
       `And shout towards the house`,
       `"Cook, mom, dinner,`,
       `And to my lot"`,
       `"Do you think, mother,`,
       `That I'm not crying here`,
       `Behind bitter tears`,
       `I don't see the world."`,
       `"Do you think, mother,`,
       `What am I here like in paradise`,
       `Come and see`,
       `How I burn here."`,
       `"Remember me, mother,`,
       `At least once on Saturday`,
       `As I remember`,
       `When I go to work."`,
       `"Remember me, mother,`,
       `at least once on Sunday`,
       `as I remember`,
       `Making the bed."`,
       `"Remember me, mother,`,
       `at least once on Tuesday`,
       `as I remember`,
       `Forty times a day...`,
      ],
    },
  ],

//   ishow milenki
  [
    {
      lang: `PL`,
      songName: `Szedł mileńki po łące`,
      songText: [
        `Szedł mileńki po łące`,
        `A ja młoda - brzegiem.`,
        `Machnął mileńki chusteczką`,
        `A ja ręką prawą.`,
        `Podaj rękę przez rzeczkę`,
        `Przez bystrą rzekę.`,
        `Rzeczka jest szeroka`,
        `Strome brzegi ma.`,
        `Rzeka się rozzłościła`,
        `Kiedy fala uderzyła,`,
        `Kiedy fala uderzyła`,
        `W strome brzegi dwa.`,
        `Idzie już mój czas`,
        `Idzie mroźna zima.`,
        `Nie ma śladu na drodze.`,
        `Nie ma mego miłego.`,
      ],
    },
    {
      lang: `BY`,
      songName: `Ішоў міленькі`,
      songText: [
        `Ішоў міленькі лужочкам,`,
        `А я млада беражком.`,
        `Махнуў міленькі платочкам,`,
        `А я праваю рукой.`,
        `Чэраз рэчку падай ручку,`,
        `Чэраз быструю раку.`,
        `Гэта рэчачка шырока,`,
        `Да крутыя берага.`,
        `Гэта рэчка рассярчала,`,
        `Як ударыла вална, `,
        `Як ударыла вална `,
        `Да ў крутыя берага. `,
        `Наступае маё ўрэмя `,
        `Усё халодная зіма, `,
        `Нету следу на дарожцы, `,
        `Майго мілага няма.`,
    ],
    },
    {
      lang: `EN`,
      songName: `Walked a  dear along the meadow`,
      songText: [
        `Walked a  dear along the meadow,`,
        `And I'm  a young girl – along the coast.`,
        `My dear waved by handkerchief`,
        `And I waved by my right hand.`,
        `Throw a pen across the river`,
        `Through the fast river.`,
        `This river is wide`,
        `Yes, steep shores.`,
        `This river is angry`,
        `How the wave hit.`,
        `How the wave hit`,
        `Yes, steep banks.`,
        `My time is coming`,
        `All cold winter.`,
        `No trace on the track`,
        `My dear has gone.`,
      ],
    },
  ],

//   a u sadze ruzsha
  [
    {
      lang: `PL`,
      songName: `Rośnie róża w sadzie`,
      songText: [
        `Rośnie róża w sadzie`,
        `O mój drogi Boże!`,
        `Nieszczęsny mój los.`,
        `Ani chrzcin,`,
        `Ani kolędy,`,
        `Ani rodzonej Matki.`,
        `Posłałabym`,
        `Czarnego ptaka`,
        `Na ten świat`,
        `Po mamę.`,
        `Sokoła`,
        `Do Ukrainy`,
        `Do swojej ojczyzny.`,
        `Leci sokół`,
        `Nie doleci`,
        `Mama długo czeka.`,
        `"Och, chciałbym ja wstać,`,
        `Moje dziecko,`,
        `Porządki robić!`,
        `Ale święta ziemia`,
        `Ciąży mi na piersi`,
        `Nie mogę ja wstać!`,
        `Deski sosnowe`,
        `Ścisnęły mi nogi`,
        `Nie mogę ja pójść."`,
      ],
    },
    {
      lang: `BY`,
      songName: `А ў садзе ружа`,
      songText: [
        `А ў садзе ружа, `,
        `Мілы мой Божа - `,
        `Несчасна мая доль. `,
        `Не порадзіны, `,
        `Не колядзіны - `,
        `Не родныя мамкі. `,
        `Пасылала б я `,
        `Чорну галачку `,
        `На той свет `,
        `Па мамку. `,
        `Сакаліначку `,
        `На Украіначку `,
        `На сваю радзімку. `,
        `Саколік ляціць `,
        `Не далётае `,
        `Мамачка даўно ждзёць. `,
        `"Ой, рада б я ўстаць, `,
        `Мае дзіцяці - `,
        `Парадак павесці. `,
        `Бо сыра зямля `,
        `На грудзі лягла - `,
        `Не магу я Устаці. `,
        `Сасновы дошкі `,
        `Сціснулі ножкі - `,
        `Не магу пайсці, ісці."`,
    ],
    },
    {
      lang: `EN`,
      songName: `A rose grows in the garden`,
      songText: [
        `A rose grows in the garden`,
        `My dear God`,
        `My unfortunate fate.`,
        `Not a christening`,
        `Not carols`,
        `Not native mothers.`,
        `I would send`,
        `black tick`,
        `To that world`,
        `For mom.`,
        `Sokolinochka`,
        `To Ukrainochka`,
        `To your homeland.`,
        `The falcon is flying`,
        `Doesn't fly`,
        `Mom has been waiting.`,
        `"Oh, I'd love to get up,`,
        `My child`,
        `Put in order!`,
        `But damp earth`,
        `Lie on the chest`,
        `I can't get up!`,
        `Pine boards`,
        `Squeeze my legs`,
        `Can not walk."`,
      ],
    },
  ],

//   garela sosna
  [
    {
      lang: `PL`,
      songName: `Płonęła sosna`,
      songText: [
        `Oj, wiosna!`,
        `Oj, piękna!`,
        `Co tym nam`,
        `Przyniosłaś?`,
        `Wiosnaczucha-bołbotucha`,
        `Kracze kruk`,
        `Sera chce!`,
        `Sera chce,`,
        `Płacze dziewczyna`,
        `Za mąż chce.`,
        `Nie kracz, kruku`,
        `Jeszcze się nakraczesz,`,
        `Nie płacz dziewczyno,`,
        `Jeszcze się napłaczesz!`,
        `Kracze kruk,`,
        `Zjadł sera,`,
        `Dziewczyna płacze`,
        `syna urodziła.`,
        ``,
        `Płonęła sosna,`,
        `Płonęła.`,
        `Pod nią dziewczyna`,
        `Stanęła.`,
        `Jasny warkocz czesała.`,
        `Oj, warkocze-warkocze`,
        `Wy moje!`,
        `Mało służyłyście`,
        `Wy u mnie!`,
        `Oj, dłużej służyć`,
        `nie będziecie`,
        `Pod biały welon`,
        `Pójdziecie!`,
      ],
    },
    {
      lang: `BY`,
      songName: `Гарэла сосна, палала`,
      songText: [
        `Агу, вясна! `,
        `Агу, красна! `,
        `А што ж ты нам прынесла? `,
        `Весначуха-балбатуха, `,
        `Воран крача- сыра хоча! `,
        `Дзеўка плача - замуж хоча! `,
        `Не крач, воран - накрачэшся! `,
        `Не плач, дзеўка - наплачэшся! `,
        `Воран крача-сыра з'еўшы, `,
        `Дзеўка плача сына меўшы. `,
        ` `,
        `Гарэла сосна, палала. `,
        `Пад ёю дзеўка стаяла. `,
        `Русую косу часала. `,
        `"Ой, косы-косы `,
        `Вы ж мае! `,
        `Мала служылі `,
        `Вы ў мяне! `,
        `Ой, больш служыць `,
        `Не будзеце! `,
        `Пад белы вялён (вэлюм) `,
        `Пойдзеце!"`,
    ],
    },
    {
      lang: `EN`,
      songName: `A pine is burning and blazing.`,
      songText: [
        `Oh spring!`,
        `Oh red!`,
        `What did you bring for us?`,
        `Vesnachukha-talker`,
        `Raven croaks`,
        `He wants cheese!`,
        ` He wants cheese`,
        `girl is crying`,
        `Wants to get married.`,
        `Don't croak, raven`,
        `get high`,
        `Don't cry girl`,
        `You will cry!`,
        `Raven croaks,`,
        `eating cheese,`,
        `The girl is crying`,
        `having a son.`,

        `A pine is burning and blazing.`,
        `a girl is standing under the pine.`,
        `A girl is brushing her Fairy scythe .`,
        `Oh, braids`,
        `You are mine!`,
        `Little served`,
        `I have you!`,
        `You won't serve more`,
        `Under a white veil`,
        `Will be!`,
      ],
    },
  ],

//   los
  [
    {
      lang: `PL`,
      songName: `Oj, złapali siwego łosia w grochu`,
      songText: [
        `Oj, złapali `,
        `siwego łosia w grochu.`,
        `Jak usłyszała`,
        `to jego stara`,
        `łosza na łące.`,
        `zrzuciła swoje`,
        `przepiękne rogi`,
        `pod nogi.`,
        `"Niechaj te rogi`,
        `me piękne rogi`,
        `Przepadną!`,
        `Tam gdzie mojego`,
        `siwego łosia`,
        `Prowadzą."`,
      ],
    },
    {
      lang: `BY`,
      songName: `Ой злавілі лося ў гаросе`,
      songText: [
        `Ой злавілі `,
        `Ды сівогога лося У гаросе. `,
        `Як і пачула `,
        `Яго старая ласіца У лузе. `,
        `Як і кінула `,
        `Крутыя рогі пад ногі. `,
        `"Няхай мае `,
        `Крутыя рогі прападуць! `,
        `Куды ж майго `,
        `Сівога лася павядуць?"`,
    ],
    },
    {
      lang: `EN`,
      songName: `Oh, they caught a grey-haired elk in peas.`,
      songText: [
        `Oh, they caught grey-haired elk in peas.`,
        `When his old moose heard it  in the meadow.`,
        `I threw my tough horns under your feet.`,
        `"Let my tough horns will be lost!`,
        `Where is my old moose they will lead"`,
      ],
    },
  ],
];


