export const spellContent = [
  {
    lang: `PL`,
    spellName: `(Zaklęcie przed złym okiem)`,
    spellText: [
      `Boże błogosław,`,
      `Boże chroń:`,
      `Od suszy, od czarów,`,
      `Od uroku i od klątwy,`,
      `I od dwunastu carów,`,
      `I od dwunastu królów,`,
      `I od dwunastu czarów`,
      `I od dwunastu uroków.`,
      `Skąd przyszliście?`,
      `Czemu się przyczepiliście?`,
      `Czy dla radości?`,
      `Czy dla zazdrości?`,
      `Czy na kłótnię?`,
      `Czy na głupotę?`,
      `Od pięknych dziewczyn,`,
      `Od udatnych młódek,`,
      `Od starych starców,`,
      `Od młodych młodzieńców, `,
      `od pierworodnego, od drugorodnego,`,
      `od czarnego oka, od ciemnego wzroku,`,
      `od krzywego patrzącego,`,
      `od zadziornego, z boku zaglądającego.`,
      `Nie ma tu Was być,`,
      `Nie możecie żyć,`,
      `Prytki-prystawki!`,
      `Idźcie na mchy, na bagna,`,
      `Na zgniłe kłody,`,
      `W bory drzemiące, `,
      `Do gęstego boru,`,
      `Na trzęsawiska,`,
      `Tam wasz ród i wasze plemię,`,
      `Tam Wasze jadła słodkie,`,
      `A słudze Iwanowi`,
      `Dobrego zdrowia.`,
    ],
  },
  {
    lang: `BY`,
    spellName: `(Супраць ліхога вока)`,
    spellText: [
      `Госпадзі, баславі,`,
      `Госпадзі, пасабі!`,
      `Ад прысух, ад нетух,`,
      `Ад урокаў, ад парокаў, `,
      `І дзвенаццаці цароў, `,
      `І дзвенаццаці каралёў, `,
      `І дзвенаццаці прысух, `,
      `І дзвенаццаці нетух. `,
      `І адкуда вы прыкаціліся?`,
      `І на што вы спахваціліся?`,
      `Ілі на радасьцях? `,
      `Ілі на завісьцях? `,
      `Ілі на спорных? `,
      `Ілі на вздорных? `,
      `Ад красных дзявіц,`,
      `Ад удалых маладзіц,`,
      `Ад старых старыкоў, `,
      `Ад маладых маладцоў,`,
      `І ад перважонца, `,
      `І ад другажонца, `,
      `І ад чорнага глаза, `,
      `І ад чорнага, падзадорнага, `,
      `І з боку сматрашчага, `,
      `З боку захадзяшчага.`,
      `Вам тут не быць, не жыць, `,
      `Прыткі прыстаўкі! `,
      `Ідзіце вы на мхі, на балота, `,
      `На гнілыя калода, `,
      `На леса дрэмучыя, `,
      `На места тапучыя, `,
      `Там ваш род-племені, `,
      `Явства сахарныя, `,
      `А рабу Івану добрага здароўя`,
    ],
  },
  {
    lang: `EN`,
    spellName: `(Against the evil eye)`,
    spellText: [
      `God bless`,
      `God help me!`,
      `From dry (drought), from evil eye,`,
      `From lessons, from vices flaws),`,
      `And twelve kings`,
      `And twelve kings`,
      `And twelve droughts`,
      `And twelve evil eye .`,
      `And where did you come from?`,
      `And what were you up to?`,
      `Is it for joy?`,
      `Is it envy?`,
      `Whether on controversial?`,
      `Whether on absurd?`,
      `From the red (red it means young) girls`,
      `From young women,`,
      `From old people`,
      `From young fellows`,
      `from the firstborn, from the friend,`,
      `from the black eye, from the black,`,
      `prankster, from looking askance,`,
      `from the side of the person entering.`,
      `You shouldn't be here`,
      `Don't live`,
      `Prytki-prefixes!`,
      `you go to the mosses,`,
      `To the swamps`,
      `On rotten decks`,
      `To dense forests,`,
      `To stomping places, there is your kind-tribe,`,
      `sugar jellies,`,
      `And slave Ivan`,
      `Good health.`,
    ],
  },
];