export const spellContent = [
  {
    lang: `BY`,
    spellName: `(Супраць ліхога вока)`,
    spellText: [
      `Госпадзі, баславі,`,
      `Госпадзі, пасабі!`,
      `Ад прысух, ад нетух,`,
      `Ад урокаў, ад парокаў, `,
      `І дзвенаццаці цароў, `,
      `І дзвенаццаці каралёў, `,
      `І дзвенаццаці прысух, `,
      `І дзвенаццаці нетух. `,
      `І адкуда вы прыкаціліся?`,
      `І на што вы спахваціліся?`,
      `Ілі на радасьцях? `,
      `Ілі на завісьцях? `,
      `Ілі на спорных? `,
      `Ілі на вздорных? `,
      `Ад красных дзявіц,`,
      `Ад удалых маладзіц,`,
      `Ад старых старыкоў, `,
      `Ад маладых маладцоў,`,
      `І ад перважонца, `,
      `І ад другажонца, `,
      `І ад чорнага глаза, `,
      `І ад чорнага, падзадорнага, `,
      `І з боку сматрашчага, `,
      `З боку захадзяшчага.`,
      `Вам тут не быць, не жыць, `,
      `Прыткі прыстаўкі! `,
      `Ідзіце вы на мхі, на балота, `,
      `На гнілыя калода, `,
      `На леса дрэмучыя, `,
      `На места тапучыя, `,
      `Там ваш род-племені, `,
      `Явства сахарныя, `,
      `А рабу Івану добрага здароўя`,
    ],
  },
  {
    lang: `EN`,
    spellName: `(Against the evil eye)`,
    spellText: [
      `Lord, bless,`,
      `Lord, help! `,
      `From droughts, from droughts, `,
      `From lessons, from vices,`,
      `And the twelve kings `,
      `And the twelve kings `,
      `And twelve dry,`,
      `And twelve netuh. `,
      `And where did you come from? `,
      `And what did you do? `,
      `Or on joys? `,
      `Or on envy? `,
      `Or on the controversial? `,
      `Or on nonsense? `,
      `From red girls `,
      `From successful young women, `,
      `From old men, `,
      `From young people, `,
      `And from the beginning, `,
      `And from the second spouse, `,
      `And from the black eye, `,
      `And from black, fiery, `,
      `And from the side of the viewer, `,
      `From the western side. `,
      `You should not be here, do not live, `,
      `Attached prefixes! `,
      `Do you go to the moss, to the swamp, `,
      `On rotten logs, `,
      `Dozing in the forest, `,
      `Instead of trampling, `,
      `There is your kindred, `,
      `The phenomenon of sugar, `,
      `And good health to my servant Ivan`,
    ],
  },
  {
    lang: `PL`,
    spellName: `(Zaklęcie przed złym okiem)`,
    spellText: [
      `Boże błogosław,`,
      `Boże chroń:`,
      `Od suszy, od czarów,`,
      `Od uroku i od klątwy,`,
      `I od dwunastu carów,`,
      `I od dwunastu królów,`,
      `I od dwunastu czarów`,
      `I od dwunastu uroków.`,
      `Skąd przyszliście?`,
      `Czemu się przyczepiliście?`,
      `Czy dla radości?`,
      `Czy dla zazdrości?`,
      `Czy na kłótnię?`,
      `Czy na głupotę?`,
      `Od pięknych dziewczyn,`,
      `Od udatnych młódek,`,
      `Od starych starców,`,
      `Od młodych młodzieńców, `,
      `od pierworodnego, od drugorodnego,`,
      `od czarnego oka, od ciemnego wzroku,`,
      `od krzywego patrzącego,`,
      `od zadziornego, z boku zaglądającego.`,
      `Nie ma tu Was być,`,
      `Nie możecie żyć,`,
      `Prytki-prystawki!`,
      `Idźcie na mchy, na bagna,`,
      `Na zgniłe kłody,`,
      `W bory drzemiące, `,
      `Do gęstego boru,`,
      `Na trzęsawiska,`,
      `Tam wasz ród i wasze plemię,`,
      `Tam Wasze jadła słodkie,`,
      `A słudze Iwanowi`,
      `Dobrego zdrowia.`,
    ],
  },
];
